const GET_SLIDE_API = process.env.REACT_APP_GET_SLIDE_API
const CREATE_SLIDE_API = process.env.REACT_APP_CREATE_SLIDE_API
const UPDATE_SLIDE_API = process.env.REACT_APP_UPDATE_SLIDE_API
const DELETE_SLIDE_API = process.env.REACT_APP_DELETE_SLIDE_API

export {
        GET_SLIDE_API,
        CREATE_SLIDE_API,
        UPDATE_SLIDE_API,
        DELETE_SLIDE_API 
    }